---
# Docker默认配置

docker_version: "24.0.7"
docker_data_dir: "/var/lib/docker"
docker_registry_mirrors:
  - "https://registry.docker-cn.com"
  - "https://mirror.baidubce.com"
  - "https://hub-mirror.c.163.com"
docker_insecure_registries: []
docker_log_max_size: "100m"
docker_log_max_file: "3"
docker_enable_ipv6: false
